[tool.cibuildwheel]
skip = "cp36-* *_i686 *-musllinux_* *-macosx_* *-win_* *-win32"
before-all = "yum install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm && yum install --nogpgcheck -y SFCGAL SFCGAL-devel"
environment = { CFLAGS = "-I/usr/local/include" }

#test-requires = ["pytest"]
#test-command = "pytest {project}"
