site_name: PySFCGAL - Documentation
repo_name: "pysfcgal"
repo_url: "https://gitlab.com/sfcgal/pysfcgal/"

theme:
  name: material
  features:
    - navigation.instant
    - navigation.top
    - navigation.tabs
    - navigation.hide
  logo: assets/img/sfcgal.png
  favicon: assets/img/sfcgal.png
  repo_icon: "gitlab"
  palette:
     primary: custom
     accent: custom


markdown_extensions:
  - attr_list
  - admonition

plugins:
- search
- mkdocstrings:
    default_handler: python  # optional
    handlers:
      python:
        options:
          docstring_style: numpy

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - User guide:
        - Installation: user_guide/build.md
  - API Reference:
        - API: api_reference/api.md
