name: Build

on: [push, pull_request]

jobs:
  build_wheels_linux:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
      - uses: actions/checkout@v2

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.6.1
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  build_msys:
    name: Build package on MSYS2/mingw64
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: actions/checkout@v2

      - name: 'Setup MSYS2/mingw64'
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: >-
            git
            make
          pacboy: >-
            toolchain:p
            cmake:p
            ninja:p
            cgal:p
            sfcgal:p
            python:p
            python-cffi:p
            python-pip:p
            python-setuptools:p
            python-wheel:p

      - name: Build package
        run: |
          MSYSTEM= /mingw64/bin/python3 setup.py build
          MSYSTEM= /mingw64/bin/python3 setup.py install

      - name: Test package
        run: |
          MSYSTEM= /mingw64/bin/pip3 install pytest
          MSYSTEM= pytest

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
